name: build

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        pull: true
        push: true
        tags: ${{ env.IMAGE_NAME }}
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}
        cache-to: type=inline
